---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: _pages/en
  label: Pages- ENG
  create: all
  match: "**/*"
  new_doc_ext: md
- type: directory
  path: _pages/fr
  label: Pages - FR
  create: all
  match: "**/*"
  new_doc_ext: md
- type: directory
  path: collections/_communities/en
  label: Communities - ENG
  create: all
  match: "**/*"
  new_doc_ext: ",md"
- type: directory
  path: collections/_communities/fr
  label: Communities - FR
  create: all
  match: "**/*"
  new_doc_ext: md
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
