---
new_page_extension: md
auto_deploy: true
admin_path: "/admin/"
webhook_url: 
sections:
- type: heading
  label: Posts
- type: directory
  path: collections/_posts/fr
  label: Actualités - FR
  create: documents
  match: "**/*"
  new_doc_ext: md
- type: directory
  path: collections/_posts/en
  label: Actualités - ENG
  create: documents
  match: "**/*"
  new_doc_ext: md
- type: heading
  label: Projects
- type: directory
  path: collections/_projects/fr
  label: Projets  - FR
  create: all
  match: "**/*"
  new_doc_ext: md
- type: directory
  path: collections/_projects/en
  label: Projets - ENG
  create: all
  match: "**/*"
  new_doc_ext: md
- type: heading
  label: Pages of the Menu
- type: directory
  path: _pages/fr
  label: Pages - FR
  create: all
  match: "**/*"
  new_doc_ext: md
- type: directory
  path: _pages/en
  label: Pages- ENG
  create: all
  match: "**/*"
  new_doc_ext: md
- type: heading
  label: Team
- type: directory
  path: collections/_people/fr
  label: People - FR
  create: all
  match: "**/*"
  new_doc_ext: md
- type: directory
  path: collections/_people/en
  label: People - ENG
  create: all
  match: "**/*"
  new_doc_ext: md
- type: heading
  label: Communities at LF2L
- type: directory
  path: collections/_communities/fr
  label: Communities - FR
  create: all
  match: "**/*"
  new_doc_ext: md
- type: directory
  path: collections/_communities/en
  label: Communities - ENG
  create: all
  match: "**/*"
  new_doc_ext: ",md"
- type: heading
  label: Concept LF2L
- type: directory
  path: collections/_concept/fr
  label: Concept - FR
  create: all
  match: "**/*"
  new_doc_ext: md
- type: directory
  path: collections/_concept/en
  label: Concept - ENG
  create: all
  match: "**/*"
  new_doc_ext: md
- type: heading
  label: Practical Info
- type: directory
  path: collections/_info/fr
  label: Info - FR
  create: all
  match: "**/*"
  new_doc_ext: md
- type: directory
  path: collections/_info/en
  label: Info - ENG
  create: all
  match: "**/*"
  new_doc_ext: md
- type: directory
  path: collections/_place-tools/fr
  label: Place-tools - FR
  create: all
  match: "**/*"
  new_doc_ext: md
- type: directory
  path: collections/_place-tools/en
  label: Place-tools - ENG
  create: all
  match: "**/*"
  new_doc_ext: md
upload_dir: uploads
public_path: "/uploads"
front_matter_path: "/uploads"
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
instant_preview: 
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
  preview_command: bundle exec jekyll build --drafts --unpublished --future -d _site
