---
new_page_extension: md
auto_deploy: false
admin_path: "/admin/"
webhook_url: 
sections:
- type: directory
  path: collections/_people/fr
  label: People - FR
  create: all
  match: "**/*"
  new_doc_ext: md
- type: directory
  path: collections/_people/en
  label: People - ENG
  create: all
  match: "**/*"
  new_doc_ext: md
- type: directory
  path: _pages/fr
  label: Pages - FR
  create: all
  match: "**/*"
  new_doc_ext: md
- type: directory
  path: _pages/en
  label: Pages- ENG
  create: all
  match: "**/*"
  new_doc_ext: md
- type: directory
  path: collections/_communities/fr
  label: Communities - FR
  create: all
  match: "**/*"
  new_doc_ext: md
- type: directory
  path: collections/_communities/en
  label: Communities - ENG
  create: all
  match: "**/*"
  new_doc_ext: ",md"
- type: directory
  path: collections/_concept/fr
  label: Concept - FR
  create: all
  match: "**/*"
  new_doc_ext: md
- type: directory
  path: collections/_concept/en
  label: Concept - ENG
  create: all
  match: "**/*"
  new_doc_ext: md
- type: directory
  path: collections/_info/fr
  label: Info - FR
  create: all
  match: "**/*"
  new_doc_ext: md
- type: directory
  path: collections/_info/en
  label: Info - ENG
  create: all
  match: "**/*"
  new_doc_ext: md
- type: directory
  path: collections/_projects/fr
  label: Projets  - FR
  create: all
  match: "**/*"
  new_doc_ext: md
- type: directory
  path: collections/_projects/en
  label: Projets - ENG
  create: all
  match: "**/*"
  new_doc_ext: md
- type: directory
  path: collections/_place-tools/fr
  label: Place-tools - FR
  create: all
  match: "**/*"
  new_doc_ext: md
- type: directory
  path: collections/_place-tools/en
  label: Place-tools - ENG
  create: all
  match: "**/*"
  new_doc_ext: md
upload_dir: uploads
public_path: assets/images/uploads
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
